# Generated by Django 5.1.4 on 2025-10-02 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0001_initial"),
        ("reels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reel",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="artist.artist"
            ),
        ),
    ]
