# Generated by Django 5.1.4 on 2025-10-14 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_artist_event_date_alter_event_artist"),
        ("reels", "0002_alter_reel_artist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reel",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.artist"
            ),
        ),
    ]
