# Generated by Django 5.1.4 on 2025-09-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventticket",
            name="sold",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
