# Generated by Django 5.1.4 on 2025-10-02 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_eventticket_sold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        migrations.RemoveField(
            model_name="eventticket",
            name="sold",
        ),
        migrations.AddField(
            model_name="eventticket",
            name="ticket_type",
            field=models.CharField(
                choices=[("Regular", "Regular"), ("VIP", "VIP"), ("VVIP", "VVIP")],
                default="Regular",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.category",
            ),
        ),
        migrations.AlterField(
            model_name="eventhistory",
            name="interaction_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="eventticket",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="eventticket",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="venue",
            name="capacity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="TicketQR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.eventticket",
                    ),
                ),
            ],
        ),
    ]
