# Generated by Django 5.1.4 on 2025-10-02 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0001_initial"),
        ("events", "0003_remove_event_date_remove_eventticket_sold_and_more"),
        ("reels", "0002_alter_reel_artist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="artist.artist"
            ),
        ),
        migrations.DeleteModel(
            name="Artist",
        ),
    ]
