# Generated by Django 5.1.4 on 2025-10-15 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_artist_event_date_alter_event_artist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="name",
            new_name="title",
        ),
    ]
