# Generated by Django 5.1.4 on 2025-10-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_rename_name_event_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="bio",
        ),
        migrations.AlterField(
            model_name="event",
            name="artist",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="eventticket",
            name="quantity",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
