# Generated by Django 5.1.4 on 2025-10-02 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_artistprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ArtistProfile",
        ),
    ]
