# Generated by Django 5.1.4 on 2025-10-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_delete_artistprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_on_event",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                default="profiles/default.png", upload_to="profiles/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
