# Generated by Django 5.1.4 on 2025-10-14 23:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0001_initial"),
        ("events", "0005_artist_event_date_alter_event_artist"),
        ("reels", "0003_alter_reel_artist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="Artist",
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="following_artists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
