# Generated by Django 5.1.4 on 2025-10-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reminded",
            field=models.BooleanField(default=False),
        ),
    ]
