# Generated by Django 5.1.4 on 2025-10-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_reminded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="reminded",
        ),
    ]
